### ISSUE TITLE
Finalise AWS tag API

### ISSUE THREAD

**Issue by mrjackdavis** [Trioxis/aws-backup-manager#2]
The AWS tag API needs to be finalised asap

Trioxis' predecessor (private) project required the following of an instance

> 1. Instance must be running
> 2. Instance must be in production, i.e. have Environment tag === "Production"
> 3. Instances must have `BackupFrequency`, `BackupVolumes` and `BackupCleanupLength` tags

However, as discussed with @Dermah, we're better off tagging EBS' and requiring the following:

1. `BackupFrequency` - Comma delimited string of how often to backup
2. `BackupTTL` - Comma delimited string of time to live in hours
3. `Backup` - If "true" this should be backed up
4. `Name` or `BackupName` - Human friendly name of the backup

**Comment by mrjackdavis** [comment]
Might I suggest a few amendments. The following tags are required:

1. `BackupConfig` - Comma delimited string of how often to backup including TTL
2. `Name` or `BackupName` - Human friendly name of the backup

`BackupConfig` can take a set of aliases such as `hourly,weekly,monthly,yearly` each with an implied TTL `24`,`4`,`12`,`never` respectively. Or if you'd like to be more complex, one could do `[1,12],[12,]`. Which would be:

- `[1,12]` Backup ever 1 hour, with a TTL of 12 hours
- `[12,14]` Backup every 12 hours with a TTL of 168 hours

Therefore aliases are just shortcuts

- `Hourly` == `[1,24]`
- `Daily` == `[24,168]`
- `Weekly` == `[168,672]`

**Comment by Dermah** [comment]
I like this suggestion and we should additionally be careful of the following:

* EC2 objects may only have a maximum of 8 tags so ideally we need to take up only one tag at most. 
* We should take in to account that we may want to change the way the `BackupConfig` value is interpreted, so the key here should include some kind of API version information. Something like `BackupConfig-v1`
* We may in future drop the words `BackupConfig` altogether in favour of something more recognisable and brand friendly.

**Comment by mrjackdavis** [comment]
I've made #3 in regards to brand friendliness

I agree with all points.
Not so much a fan of the mixed case in `BackupConfig-v1`. Would prefer `BackupConfigV1` or `backup-config-v1`

**Comment by Dermah** [comment]
In the style of the tags automatically added by AWS e.g. `aws:cloudformation:stack-id`, how about `backups:config-v1` ?
