### ISSUE TITLE
Implement listSnapshots

### ISSUE THREAD

**Issue by Dermah** [Trioxis/aws-backup-manager#6]
Wait it sorta works already. 

But maybe there is something that could be done to improve how it works? 

At the moment it returns a list of all the snapshots you can see, but that isn't very helpful. It should really only return snapshots that are owned by the account you are using because they are the only ones you can manage and care about. 

What format should the data be in? It would probably be best to return only information that is necessary to perform our backup tasks

We should not bother returning snapshots that don't have the `backups:config-v0` tag?

To get started, make a new branch, run `npm run watch` then find the `describe('listSnapshots', () => {` in `_TestEC2Store.js` and remove all the `.skip` statements within this block. You should see tests failing in the terminal. You'll need to implement the `listSnapshots` function in `EC2Store.js` to pass these tests. You should also fix tests that may not test functionality correctly, and add new tests that check additional functionality.

- [x] Remove `.skip` statements to enable failing tests
- [x] Implement `listSnapshots`
- [x] Add more tests that test desired functionality of `listSnapshots`

**Comment by mrjackdavis** [comment]
I agree, all snapshots without the required configuration tag should be filtered
